#!/bin/bash
## Pruebas de rendimiento sobre sistemas de archivos btrfs

# creamos archivo en bruto que representara una partición virtual
# crearemos una particion apartir de un archivo a manera de estudio
# pero tambien puede aplicacar sobre particiones nativas
# creamos con el mandato dd una particion con datos nulos de 100000 bloques (1 bloque = 512 Bytes)
dd if=/dev/zero of=btrfs.fs count=100000
# formatear el archivo creado
mkfs.btrfs btrfs.fs
#crear carpeta de montaje
mkdir /test/particion_btrfs
# Mapear el archivo a loop, btrfs.fs queda referenciado por /dev/loop2
losetup /dev/loop2 btrfs.fs
# montamos el archivo al directorio creado con anterioridad
mount -t btrfs /dev/loop2 /test/particion_btrfs

