#!/bin/bash
## Pruebas de rendimiento sobre sistemas de archivos EXT4

# creamos archivo en bruto que representara una partición virtual
# crearemos una particion apartir de un archivo a manera de estudio
# pero tambien puede aplicacar sobre particiones nativas
# creamos con el mandato dd una particion con datos nulos de 100000 bloques (1 $
dd if=/dev/zero of=ext4.fs count=100000
# formatear el archivo creado
mkfs.ext4 ext4.fs
#crear carpeta de montaje
mkdir /test/particion_ext4
# Mapear el archivo a loop, ext4.fs queda referenciado por /dev/loop1
losetup /dev/loop1 ext4.fs
# montamos el archivo al directorio creado con anterioridad
mount -t ext4 /dev/loop1 /test/particion_ext4
