#!/bin/bash
## Pruebas de rendimiento sobre sistemas de archivos NTFS

# creamos archivo en bruto que representara una partición virtual
# crearemos una particion apartir de un archivo a manera de estudio
# pero tambien puede aplicacar sobre particiones nativas
# creamos con el mandato dd una particion con datos nulos de 100000 bloques (1 bloque = 512 Bytes)
dd if=/dev/zero of=ntfs.fs count=100000
# formatear el archivo creado
sudo mkfs.ntfs -v -L ntfs /dev/loop3
#mkntfs --fast ntfs ntfs.fs
#crear carpeta de montaje
mkdir /test/particion_ntfs
# Mapear el archivo a loop, ntfs.fs queda referenciado por /dev/loop3
losetup /dev/loop3 ntfs.fs
# montamos el archivo al directorio creado con anterioridad
mount -t ntfs-3g /dev/loop3 /test/particion_ntfs

